//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheepshead.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hand()
        {
            this.Tricks = new HashSet<Trick>();
        }
    
        public int Id { get; set; }
        public string Blinds { get; set; }
        public string Buried { get; set; }
        public string RefusingPick { get; set; }
        public int StartingPlayerId { get; set; }
        public Nullable<int> PickerId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string PartnerCard { get; set; }
        public System.Guid GameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trick> Tricks { get; set; }
    }
}
