

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sheepshead.Model.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SheepsheadEntities : DbContext
{
    public SheepsheadEntities()
        : base("name=SheepsheadEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Game> Game { get; set; }

    public virtual DbSet<Hand> Hand { get; set; }

    public virtual DbSet<Participant> Participant { get; set; }

    public virtual DbSet<Trick> Trick { get; set; }

    public virtual DbSet<TrickPlay> TrickPlay { get; set; }

    public virtual DbSet<Coin> Coin { get; set; }

    public virtual DbSet<Point> Point { get; set; }

}

}

